export const RevenueReports = 'Revenue Report';
export const Earning = 'Earning';
export const Transactions = 'Transactions';
export const Visitors = 'Visitors';
export const NewUpdate = 'New & Update';
export const ToDoList = 'To Do List';
export const Addtask = 'Add task';
export const RecentActivitys = 'Recent Activity';
export const BrowserStates = 'Browser States';
export const AddNewUser = 'Add New User';
export const EditNewUser = 'Edit User';
export const AddNew = 'Add New';
export const AllUserss = 'Users';
export const AllCategories = 'Categories';
export const AllTags = 'Tags';
export const Account = 'Account';
export const Permission = 'Permission';
export const FirstName = 'First Name';
export const Name = 'Name';
export const Image = 'Image';
export const Phone = 'Phone';
export const EmailAddress = 'Email Address';
export const Password = 'Password';
export const ConfirmPassword = 'Confirm Password';
export const ProductInformation = 'Product Information';
export const UserInformation = 'User Information';
export const Submit = 'Submit';
export const OrderList = 'Order List';
export const OrderTracking = 'Order Tracking';
export const Cancel = 'Cancel';
export const CreateVendor = 'Create Vendor';
export const VendorList = 'Vendor List';
export const ProductsList = 'Products List';
export const AddNewProduct = 'Add New Product';
export const TranslationList = 'Translation List';
export const CurrencyRates = 'Currency Rates';
export const Taxess = 'Taxes';
export const MenuList = 'Menu List';
export const CreatedMenu = 'Created Menu';
export const Couponlist = 'Coupon List';
export const CreateCoupon = 'Create Coupon';
export const General = 'General';
export const Restriction = 'Restriction';
export const Usage = 'Usage';
export const CouponTitle = 'Coupon Title';
export const CouponCode = 'Coupon Code';
export const StartDate = 'Start Date';
export const EndDates = 'End Date';
export const FreeShipping = 'Free Shipping';
export const AllowFreeShipping = 'Allow Free Shipping';
export const Quantity = 'Quantity';
export const DiscountType = 'Discount Type';
export const Select = '--Select--';
export const Percent = 'Percent';
export const Fixed = 'Fixed';
export const Status = 'Status';
export const EnabletheCoupon = 'Enable the Coupon';
export const Products = 'Products';
export const Category = 'Category';
export const Electronics = 'Electronics';
export const Clothes = 'Clothes';
export const Shoes = 'Shoes';
export const Digital = 'Digital';
export const MinimumSpend = 'Minimum Spend';
export const MaximumSpend = 'Maximum Spend';
export const UsageLimits = 'Usage Limits';
export const PerLimited = 'Per Limited';
export const PerCustomer = 'Per Customer';
export const MenuName = 'Menu Name';
export const Description = 'Description';
export const Access = 'Access';
export const PermanentLink = 'Permanent Link';
export const EnabletheMenu = 'Enable the Menu';
export const OrderNo = 'Order #36648';
export const DateTime = 'October 21, 2021 at 9:08 pm';
export const items = '6 items';
export const TotalCost = 'Total $5,882.00';
export const Subtotal = 'Subtotal';
export const Shipping = 'Shipping';
export const TotalPrice = 'Total Price';
export const summery = 'summery';
export const shippingaddress = 'shipping address';
export const EditItems = 'Edit Items';
export const ProductDescription = 'Product Description';
export const Upsells = 'Upsells';
export const CrossSells = 'Cross-Sells';
export const ProductImages = 'Product Images';
export const Images = 'Images';
export const ThumbnailImage = 'Thumbnail Image';
export const ProductType = 'Product Type';
export const StaticMenu = 'Static Menu';
export const Simple = 'Simple';
export const Classified = 'Classified';
export const CategoryMenu = 'Category Menu';
export const Fashion = 'Fashion';
export const Furniture = 'Furniture';
export const Flower = 'Flower';
export const Vegetables = 'Vegetables';
export const Another = 'Another';
export const Subcategory = 'Subcategory';
export const SubcategoryMenu = 'Subcategory Menu';
export const Price = 'Price';
export const VideoLink = 'Video Link';
export const ProductVideos = 'Product Videos';
export const VideoProvider = 'Video Provider';
export const ProductReviews = 'Product Reviews';
export const Forgotyourpassword = 'Forgot your password?';
export const LogIn = 'Log In';
export const Logins = 'Login';
export const Pleasefillthename = 'Please fill the name';
export const Email = 'Email';
export const Country = 'Country';
export const Send = 'Send';
export const ForgotPasswords = 'Forgot Password';
export const UpdatePasswords = 'Update Password';
export const ConfirmPasswords = 'Confirm Password';
export const Confirm = 'Confirm';
export const Areyousure = 'Are you sure?';
export const ConfirmDelete = 'Confirm Delete';
export const Yes = 'Yes';
export const No = 'No';
export const OTP = 'OTP';
export const Verify = 'Verify';
export const AddCategoryss = 'Add Category';
export const UpdateCategoryss = 'Update Category';
export const AddTagss = 'Add Tag';
export const UpdateTag = 'Update Tag';
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
// export const RevenueReports = 'Revenue Report'
